---
apiVersion: v1
kind: Namespace
metadata:
  name: vpa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: davecloud
  namespace: vpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: davecloud
  template:
    metadata:
      labels:
        app: davecloud
    spec:
      containers:
      - name: davecloud
        image: dswhitehouse/stress:0.1
        resources:
          requests:
            cpu: 100m
            memory: 5Mi